# experiment name
note: demo

#project basic
task: demo  #

#model basic
lr: 0.0001
rgb_mode: False #when ee_train it must be True
use_mask: True
uv_mask: True # use mask when calculate UV loss
worker: 0
virtual_mask: False

poseseg: False
pretrain_poseseg: True

use_disc: False
mesh_disc: False

output: 'output'

#dataset
data_folder: demo

model: pose2uv_res50
epoch: 100
batchsize: 20
mode: test # train/test
gpu_index: 0

# pretrain
pretrain: True
pretrain_dir: pretrain_model/best_segnet_uv_vae_epoch036_46.359337.pkl

#visualize
viz: False
